# my monokai theme for helix
"ui.background" = { bg = "mm_background" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "mm_ui_selection" }
"comment" = { fg = "mm_comment", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursorline" = { bg = "mm_cursorline" }
"ui.text" = "white"
"operator" = "mm_text"
"ui.text.focus" = "base05"
"variable" = "mm_text"
"constant.numeric" = "mm_number"
# "constant" = { fg = "mm_text", modifiers = ["bold", "italic"] }
"attribute" = "base09"
"type" = "mm_type"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "mm_string"
"variable.other.member" = "base0B"
"constant.character.escape" = "base0C"
"function" = "mm_function"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "mm_keyword"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }


"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "act_bufferline_fg", bg = "act_bufferline_bg", modifiers = [ "bold", ] }

[palette]
base00 = "#282923" # Default Background
base01 = "#282828" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#878b91" # Selection Background
base03 = "#74705b" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f7ca88" # Classes, Markup Bold, Search Text Background
base0B = "#e0da74" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#9fe12c" # Functions, Methods, Attribute IDs, Headings
base0E = "#f9246f" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

mm_background     = "#282923"
mm_string         = "#e0da74"
mm_type           = "#67d8ef"
mm_function       = "#9fe12c"
mm_keyword        = "#f9246f"
mm_comment        = "#74705b"
mm_text           = "#f8f8ee"
mm_number         = "#ac80ff"
mm_cursorline     = "#505040"
# mm_ui_text        = "white"
act_bufferline_fg = "#770000"
act_bufferline_bg = "#e6db74"
mm_tag            = "#FFCC00"
mm_ui_selection   = "#878b91"